### ISSUE TITLE
Running v0.9.7 model in v0.9.8: TypeError Not an linear expression: -0.0

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#125]
The following v0.9.7 model (it's http://hakank.org/cpmpy/max_flow_taha.py ) throws the error `TypeError: Not an linear expression: -0.0`
```
import numpy as np
from cpmpy import *
import cpmpy.solvers
from cpmpy.solvers import *

def max_flow_taha():
  # data
  n = 5
  start = 0
  end = n - 1

  nodes = list(range(n))

  # cost matrix
  c = [[0, 20, 30, 10, 0], [0, 0, 40, 0, 30], [0, 0, 0, 10, 20],
       [0, 0, 5, 0, 20], [0, 0, 0, 0, 0]]

  # declare variables
  # We restrict upper bound of x[i,j] below
  x = intvar(0,max(c),shape=(n,n),name="x") 
  out_flow = intvar(0,10000,shape=n,name="out_flow")
  in_flow = intvar(0,10000,shape=n,name="in_flow")  

  total = intvar(0, 10000, name="total")

  model = Model(maximize=total)

  # Restrict upper bound of x[i,j]
  for i in nodes:
    for j in nodes:
      model += (x[i,j] <= c[i][j])
      
  model += (total == sum([x[start, j] for j in nodes if c[start][j] > 0]))

  for i in nodes:
    model += (in_flow[i] == sum([x[j, i] for j in nodes if c[j][i] > 0]))
    model += (out_flow[i] == sum([x[i, j] for j in nodes if c[i][j] > 0]))

  # in_flow == out_flow
  for i in nodes:
    if i != start and i != end:
      model += (out_flow[i] - in_flow[i] == 0)

  s1 = [x[i, start] for i in nodes if c[i][start] > 0]
  if len(s1) > 0:
    model += (sum([x[i, start] for i in nodes if c[i][start] > 0] == 0))

  s2 = [x[end, j] for j in nodes if c[end][j] > 0]
  if len(s2) > 0:
    model += (sum([x[end, j] for j in nodes if c[end][j] > 0]) == 0)

  ss = CPM_ortools(model)
  num_solutions = 0
  if ss.solve():
    print("total:", total.value())
    print("in_flow:", in_flow.value())
    print("out_flow:", out_flow.value())
    for i in nodes:
      for j in nodes:
        print("%2i" % x[i, j].value(), end=" ")
      print()
    print()

max_flow_taha()
```

The traceback:
```
Traceback (most recent call last):
  File "max_flow_taha.py", line 87, in <module>
    max_flow_taha()
  File "max_flow_taha.py", line 74, in max_flow_taha
    ss = CPM_ortools(model)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/ortools.py", line 91, in __init__
    super().__init__(name="ortools", cpm_model=cpm_model)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/solver_interface.py", line 83, in __init__
    self += cpm_model.constraints
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/ortools.py", line 312, in __add__
    self._post_constraint(con)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/ortools.py", line 410, in _post_constraint
    return self.ort_model.Add(lhs == rvar)
  File "/usr/local/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 298, in __eq__
    return BoundedLinearExpression(self - arg, [0, 0])
  File "/usr/local/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 219, in __sub__
    return _SumArray([self, -expr])
  File "/usr/local/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 391, in __init__
    raise TypeError('Not an linear expression: ' + str(x))
TypeError: Not an linear expression: -0.0

```

Another model that throws this error is:
* http://hakank.org/cpmpy/pandigital_numbers.py

The errors for both these models involves:
```
  ...
  File "/usr/local/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 298, in __eq__
    return BoundedLinearExpression(self - arg, [0, 0])
  File "/usr/local/lib/python3.7/site-packages/ortools/sat/python/cp_model.py", line 219, in __sub__
    return _SumArray([self, -expr])
  ...
```

**Comment by tias** [comment]
Both work fine on v0.9.7, v0.9.8 and master on my machine...

'something' is being evaluated to 0.0 instead of an expression in your case...

Try going from lazy to eager evaluation, so you know which constraint it is as it will fail as soon as it is being added, e.g. change
```
model = Model(maximize=total)
...
ss = CPM_ortools(model)
```
to
```
model = SolverLookup.get("ortools", Model(maximize=total))
...
ss = model
```
or closer to what you currently use, but we recommend SolverLookup for genericity (solvername is then only a parameter/string, instead of a full class)
```
model = CPM_ortools(Model(maximize=total))
ss = model
```

**Comment by hakank** [comment]
Thanks for the tip. 

After updating to master version, the models doesn't throw any errors anymore on my machine.
