### ISSUE TITLE
Reification problem for CPM_ortools in master (car model)

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#129]
The following stripped down version of the Car model (http:/hakank.org/cpmpy/car.py ) yields an error for ortools, which seems to indicate a problem in reification:
```
from cpmpy import *
import cpmpy.solvers
import numpy as np
from cpmpy.solvers import *

def car(num_sol=3):

  model = Model()
  
  nbCars = 6
  nbOptions = 5
  nbSlots = 10

  Options = list(range(nbOptions))
  Slots = list(range(nbSlots))

  #    car 0   1  2  3  4  5
  demand = [1, 1, 2, 2, 2, 2]

  option = [
      # car 0  1  2  3  4  5
      [1, 0, 0, 0, 1, 1],  # option 1
      [0, 0, 1, 1, 0, 1],  # option 2
      [1, 0, 0, 0, 1, 0],  # option 3
      [1, 1, 0, 1, 0, 0],  # option 4
      [0, 0, 1, 0, 0, 0]  # option 5
  ]

  slot = intvar(0,nbCars-1,shape=nbSlots,name="slot")
  setup = boolvar(shape=(nbOptions,nbSlots),name="setup")

  for o in Options:
    for s in Slots:
      model += setup[(o, s)] == Element(option[o],slot[s]) # <-- culprit

  from cpmpy.transformations.flatten_model import flatten_constraint
  for c in model.constraints:
    print("Trying",c)
    print("Flat:",flatten_constraint(c))
    Model([c]).solve()
    print()
  print("Constraints ok\n")

  ss = CPM_ortools(model)
  num_solutions = 0
  if ss.solve():
    num_solutions += 1
    print("slot:%s" % ",".join([str(slot[i].value()) for i in Slots]))

  print()
  print("num_solutions:", num_solutions)

num_sol = 3
car(num_sol)
```

Here's the output using the constraint debugger. The error is thrown for the first constraint:
```
Trying (setup[0,0]) == ([1, 0, 0, 0, 1, 1][slot[0]])
Flat: [([1, 0, 0, 0, 1, 1][slot[0]]) == (setup[0,0])]
Traceback (most recent call last):
  File "car_test.py", line 69, in <module>
    car(num_sol)
  File "car_test.py", line 55, in car
    Model([c]).solve()
  File "/usr/local/lib/python3.7/site-packages/cpmpy/model.py", line 137, in solve
    s = SolverLookup.get(solver, self)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/utils.py", line 100, in get
    return cls(model, subsolver=subname)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/ortools.py", line 91, in __init__
    super().__init__(name="ortools", cpm_model=cpm_model)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/solver_interface.py", line 83, in __init__
    self += cpm_model.constraints
  File "/usr/local/lib/python3.7/site-packages/cpmpy/solvers/ortools.py", line 310, in __add__
    cpm_cons = only_bv_implies(reify_rewrite(flatten_constraint(cpm_con)))
  File "/usr/local/lib/python3.7/site-packages/cpmpy/transformations/reification.py", line 116, in reify_rewrite
    reifexpr.args[boolexpr_index] = Operator("and", boolexpr.decompose())  # decomp() returns list
  File "/usr/local/lib/python3.7/site-packages/cpmpy/expressions/core.py", line 394, in __init__
    arg_list = flatlist(arg_list)
  File "/usr/local/lib/python3.7/site-packages/cpmpy/expressions/utils.py", line 48, in flatlist
    return list(_flatten(args))
  File "/usr/local/lib/python3.7/site-packages/cpmpy/expressions/utils.py", line 52, in _flatten
    for el in args:
TypeError: 'NoneType' object is not iterable
```

The same error occurs in the CSPLib version of the car_sequence model:  https://github.com/CPMpy/cpmpy/blob/csplib/examples/csplib/prob001_car_sequence.py

This was tested in the master version 198b6d475820439be59ac2734e9ddc09f7b0e023.
I know that this worked per 2022-06-09 08:11 (CEST) but not sure exact when the error occurred after that.

Note: If the solver is changed to `CPM_minizinc` (or `model.solve(solver="gecode")` it works.

**Comment by tias** [comment]
OK, that is related to a discussion in #96 namely an Element constraint over a Boolean array, is that a Boolean expression (and hence a valid constraint on its own) or is it an Integer expression (not valid as stand-alone constraint, only in a comparison). Here, the language treats Element(arr, idx) == BoolVar as a reification, while in fact it is and should remain a comparison.

I've pushed a fix that is valid for the current way we treat Element, and a test that might break if we change it like in (problematic) prototype #128

**Comment by hakank** [comment]
Great. I can confirm that it works (and I found no other new issues).
