### ISSUE TITLE
Model failed when ub is a variable

### ISSUE THREAD

**Issue by JayMan91** [CPMpy/cpmpy#21]
```python
from cpmpy import *
import numpy as np

jobs_data = [  # task = (machine_id: processing_time).
        {0:3,1:2,2:2},
        {0:2,2:1,1:4},
        {1:4,2:3}
    ]
makespan = IntVar(0,20)
start_time = IntVar(0, 20, shape=(3,3))
end_time = IntVar(0, makespan, shape=(3,3))
```
The error message
```python-traceback
Traceback (most recent call last):
  File "makespan.py", line 40, in <module>
    end_time = IntVar(0, makespan, shape=(3,3))
  File "/home/jayanta/Documents/cppy/cpmpy/__init__.py", line 29, in IntVar
    data = np.array([IntVarImpl(lb,ub) for _ in range(length)]) # repeat new instances
  File "/home/jayanta/Documents/cppy/cpmpy/__init__.py", line 29, in <listcomp>
    data = np.array([IntVarImpl(lb,ub) for _ in range(length)]) # repeat new instances
  File "/home/jayanta/Documents/cppy/cpmpy/variables.py", line 30, in __init__
    assert (is_int(lb) and is_int(ub))
AssertionError

```

**Comment by tias** [comment]
that is intended, a variable should have a 'pure' domain.

try:
makespan = IntVar(0,20)
start_time = IntVar(0, 20, shape=(3,3))
end_time = IntVar(0, 20, shape=(3,3)
and then something like makespan = max(end_time)?
(might have to be cpmpy.max(end_time), and you might find things not yet implemented then)

**Comment by tias** [comment]
we now overwrite max(), so
makespan = max(end_time) now works (since 0.7 or so, definitly in 0.9) and is the preferred way of modelling this
