### ISSUE TITLE
Bug: Model/__init__()

### ISSUE THREAD

**Issue by sourdough-bread** [CPMpy/cpmpy#55]
Initialisation of Model with assignment, interprets the constraints as NDVarArray instead of list. 

```Python
sudoku_model = Model(
    # Constraints on values (cells that are not empty)
    puzzle[given!=e] == given[given!=e] # numpy's indexing, vectorized equality
)
```
Following error is produced when constraints are added afterwards:

```Shell
Traceback (most recent call last):
  File "examples/test_example.py", line 31, in <module>
    sudoku_model += AllDifferent(row)
  File "/home/emilio/research/CPMpy/cpmpy/model.py", line 82, in __add__
    self.constraints.append(con)
AttributeError: 'NDVarArray' object has no attribute 'append'
```
Proposed solution in `cpmpy/model.py`:
```Python
...
        if len(args) == 0:
            self.constraints = []
        elif len(args) == 1 and is_any_list(args[0]):
            # top level list of constraints
            self.constraints = list(args[0]) ## Transform to list
        else:
            self.constraints = list(args) # instead of tuple
...
```

**Comment by tias** [comment]
fixed
