### ISSUE TITLE
solveAll using CPM_minizinc (master branch), take 2

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#92]
Thanks for fixing #90. However, for a slightly more advanced model (with more solutions than before, here 120), we're back to the asyncio problem mentioned in #90. As before it works with CPM_ortools, but throws errors with CPM_minizinc

```
import itertools
from cpmpy import *
from cpmpy.solvers import *
import numpy as np

def test_solve_all(solver="ortools"):
    print("solver:",solver)
    x = intvar(0,4, shape=4)
    m = Model(AllDifferent(x))
    if solver == "minizinc":
        s = CPM_minizinc(m)        
    else:
        s = CPM_ortools(m)

    # MiniZinc: ok
    print("just return the count:")
    num_solutions = s.solveAll() 
    print("num_solutions:", num_solutions)
    print()

    # MiniZinc: ok
    print("just return the count with solution_limit=2:")
    num_solutions = s.solveAll(solution_limit=2)
    print("num_solutions:", num_solutions)
    print()

    # MiniZinc: don't work
    num_solutions = s.solveAll(x) 
    print("num_solutions:", num_solutions)  
    print()

# solver = "ortools"
solver = "minizinc"
test_solve_all(solver)

```

The first test which count the number of solutions (120) works. 

The second test returns the restricted number of solutions (here 2) and also gives an Runtime warning (but only if the first test was run before):
```
just return the count with solution_limit=2:
/usr/local/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
num_solutions: 2
```

The third test - which enumerates all the 120 solutions - always throws the following, which seems to be the same as I noticed just a few times when reporting #90.
```
Traceback (most recent call last):
  File "../me/solve_all_test2.py", line 123, in <module>
    test_solve_all(solver)
  File "../me/solve_all_test2.py", line 68, in test_solve_all
    num_solutions = s.solveAll(x) # returns count and prints x.value(). OK
  File "/home/hakank/cppy/cpmpy/cpmpy/solvers/minizinc.py", line 502, in solveAll
    return asyncio.run(coroutine)
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 41, in run
    events.set_event_loop(loop)
  File "/usr/local/lib/python3.7/asyncio/events.py", line 757, in set_event_loop
    get_event_loop_policy().set_event_loop(loop)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 1134, in set_event_loop
    self._watcher.attach_loop(loop)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 889, in attach_loop
    self._do_waitpid_all()
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 959, in _do_waitpid_all
    self._do_waitpid(pid)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 993, in _do_waitpid
    callback(pid, returncode, *args)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 204, in _child_watcher_callback
    self.call_soon_threadsafe(transp._process_exited, returncode)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 732, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'CPM_minizinc._solveAll' was never awaited
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f1c1bb33b90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/base_subprocess.py", line 127, in __del__
  File "/usr/local/lib/python3.7/asyncio/base_subprocess.py", line 104, in close
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 522, in close
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 547, in _close
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 687, in call_soon
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

```

Environment:
- Linux Ubuntu 18.05
- Python 3.7.6
- CPMpy: master branch (commit ef6a2ab1f2782b0a93170a982ecd8e2a481cbd0e

**Comment by tias** [comment]
Hi Hakan,

I had hoped that error would magically go away, because I only learned about asyncio through the minizinc python code...

It seems to be a harmless error, e.g. 'exception ignored', and it seems to happen when we put a solution_limit; as if the 'break' in the async for loop returns too abruptly...

Actually maybe not, after the 'break' in the async for, there are now two tasks open:
{<Task pending name='Task-7' coro=<CPM_minizinc._solveAll() running at /home/tias/research/cpmpy/cpmpy/solvers/minizinc.py:271> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184]>, 
<Task pending name='Task-9' coro=<_read_all() running at /home/tias/.local/lib/python3.9/site-packages/minizinc/CLI/instance.py:540> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc474eadfd0>()]>>}

and it is the second one that is causing trouble...

I will have to ask @Dekker1...

**Comment by tias** [comment]
Hi Hakan,

Dekker1 fixed it and I was able to verify that in https://github.com/MiniZinc/minizinc-python/pull/45

It is not yet released it seems, but at least to let you know that a fix exists.

**Comment by Dekker1** [comment]
The current `develop` branch for MiniZinc Python has some other changes that relate to the output handling of the soon to be released version of MiniZinc. To ensure everything works well, the MiniZinc Python release will wait until the release of MiniZinc.

Although this problem gives a warning, it does not influence the working of the package, so I did not deem it critical. In the meantime feel free to use the `develop` branch, for which I'm of course also happy to solve any issues.

**Comment by tias** [comment]
with minizinc (the python package) 0.6.0 this now works as intended, thanks all!
